import type { Metadata } from "next";
import { cookies } from "next/headers";
import "./globals.css";
import { sora, ibmPlexSans } from "../theme/fonts";
import ThemeRegistry from "../theme/ThemeRegistry";
import { TitheModalProvider } from "@/lib/titheModalStore";
import { TitheModal } from "@/components/ui/TitheModal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  // Modo claro/oscuro resuelto en el SERVIDOR, leyendo la cookie
  // `color-mode` que `ThemeRegistry.tsx` escribe al guardar la preferencia
  // (además de `localStorage`, que ahí solo sirve como respaldo/migración).
  // El intento anterior (script bloqueante en `<head>`) seguía siendo
  // client-side: corría antes de que React hidratara, pero el HTML que
  // manda el SERVIDOR ya llegaba en modo "light" siempre, así que si la
  // preferencia real era "dark" el navegador pintaba el divider (y el resto
  // de colores dependientes del modo) claro por un instante y luego, de
  // golpe, oscuro — justo el flash que el cliente seguía viendo. Con la
  // cookie, el propio HTML generado por el servidor ya sale en el modo
  // correcto: no hay nada que corregir después en el cliente.
  // Excepción inevitable: la primerísima visita de alguien, antes de que
  // exista la cookie (ahí se usa "light" por defecto); desde esa primera
  // visita en adelante siempre coincide.
  const cookieStore = await cookies();
  const initialMode = cookieStore.get("color-mode")?.value === "dark" ? "dark" : "light";

  return (
     <html lang="es" className={`${sora.variable} ${ibmPlexSans.variable}`} suppressHydrationWarning>
      <body>
        <ThemeRegistry initialMode={initialMode}>
          {/* Montado una sola vez a nivel raíz (fase 07): el modal de Diezmo se
              abre desde 3 componentes distintos (Navbar, PageNavbar,
              MobileMenuOverlay) en cualquier página — ver `lib/titheModalStore.tsx`. */}
          <TitheModalProvider>
            {children}
            <TitheModal />
          </TitheModalProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
