import type { Metadata } from "next";
import "./globals.css";
import { sora, ibmPlexSans } from "./theme/fonts";
import ThemeRegistry from "./theme/ThemeRegistry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
     <html lang="es" className={`${sora.variable} ${ibmPlexSans.variable}`} suppressHydrationWarning>
      <body>
        <ThemeRegistry>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
